server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
<<<<<<< HEAD
  datasource:
    url: jdbc:mysql://localhost:3306/studyfy?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root1234
=======
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
>>>>>>> ee9b77bd0e89babaecda7c3a726142801936a068

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
